#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import sys
import os
import zipfile

script = os.path.basename(sys.argv[0])

if len(sys.argv) != 3 :
    print 'usage: %s hexFile dfuPkg'%script
    sys.exit(1)

hexFile = sys.argv[1]
dfuPkgFile = sys.argv[2]

hexFileName = os.path.basename(hexFile)

flashBatFileName = './flash.bat'
flashBatFile = open(flashBatFileName, 'w')
flashBatFile.write("""@echo off
:go
set/p "input=Please input enter key"
echo update starting
JLink -CommanderScript cmd.jLink
goto go
""")
flashBatFile.close()

jlinkCmdFileName = './cmd.jlink'
jlinkCmdFile = open(jlinkCmdFileName, 'w')
jlinkCmdFile.write("""device = nRF51822
if SWD
speed 4000
loadfile %s
w4 0x4001E504 0x02
w4 0x4001E508 0x3fc00
r
g
exit
""" %hexFileName)
jlinkCmdFile.close()

dfuPkg = zipfile.ZipFile(dfuPkgFile, mode='w')
dfuPkg.write(flashBatFileName)
dfuPkg.write(jlinkCmdFileName)
dfuPkg.write(hexFile, os.path.basename(hexFile))
dfuPkg.close()

os.remove(flashBatFileName)
os.remove(jlinkCmdFileName)
